# https://developers.cloudflare.com/workers/wrangler/commands/#deploy

name = "tesla"
main = "index.js"
compatibility_date = "2024-03-04"
workers_dev = false
routes = [
	{ pattern = "tesla.example.com", custom_domain = true }
]

[vars]
CLIENT_ID = "a01d7d72-eca4-45d2-a2f0-2df6d18e89a4"
# CLIENT_SECRET = "XXX" # Create as secret variable
ALLOWED_EMAIL = "my-tesla-account@example.com"
SCOPE = "openid vehicle_device_data vehicle_cmds offline_access user_data"
AUDIENCE = "https://fleet-api.prd.eu.vn.cloud.tesla.com"
PUBLIC_KEY = '''
-----BEGIN PUBLIC KEY-----
XXX
-----END PUBLIC KEY-----
'''